apiVersion: v2
name: bux
description: A Helm chart for Kubernetes

type: application

version: 0.3.0

appVersion: "1.0"

dependencies:
  - name: bux-server
    condition: bux-server.enabled
  - name: pulse
    condition: pulse.enabled
  - name: bux-console
    condition: bux-console.enabled
  - name: bux-wallet
    condition: bux-wallet.enabled

