{{- $fullName := include "block-headers-service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $domainName := .Values.global.domainName -}}
{{- $certificateArn := .Values.global.certificate_arn -}}
{{- $labels := include "block-headers-service.labels" .  -}}
{{- $enableTls := .Values.global.tls }}
---
{{if .Values.expose }}
{{- range .Values.ingress }}
{{if has .className $.Values.ingressControllers }}
{{- if and .className (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .annotations "kubernetes.io/ingress.class" .className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ .className }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ if eq .className "alb" }}
    alb.ingress.kubernetes.io/certificate-arn: {{ $certificateArn }}
  {{ end }}
spec:
  {{- if and .className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .className }}
  {{- end }}
  {{- if and $enableTls }}
  tls:
    {{- range .hosts }}
    - hosts:
        - "{{ .host  }}.{{ $domainName }}"
      secretName: {{ $fullName }}-tls
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: "{{ .host  }}.{{ $domainName }}"
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
---    
{{- end }}
{{- end }}
{{- end }}
