apiVersion: v1
kind: Secret
metadata:
  name: block-headers-service-secret
  labels:
    {{- include "block-headers-service.labels" . | nindent 4 }}
type: Opaque
data:
    {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "block-headers-service-secret") | default dict }}
    {{- $secretData := (get $secretObj "data") | default dict }}
    {{- $token := (get $secretData "block-headers-service-auth-token") | default (randAlphaNum 32 | b64enc) }}
    block-headers-service-auth-token: {{ $token | quote }}
