apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spv-wallet-web-frontend.fullname" . }}
  labels:
    {{- include "spv-wallet-web-frontend.labels" . | nindent 4 }}
data:
  env-config.json: |
    {
      "apiUrl": "https://api.{{ .Values.global.domainName }}",
      "wsUrl": "wss://api.{{ .Values.global.domainName }}/api/websocket"
    }
