apiVersion: v1
kind: Service
metadata:
  name: {{ include "spv-wallet-web-frontend.fullname" . }}
  labels:
    {{- include "spv-wallet-web-frontend.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: wallet.{{ .Values.global.domainName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spv-wallet-web-frontend.selectorLabels" . | nindent 4 }}
