apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spv-wallet-web-backend.fullname" . }}
  labels:
    {{- include "spv-wallet-web-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spv-wallet-web-backend.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spv-wallet-web-backend.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "spv-wallet-web-backend.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http

          env:
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: DB_USER
              value: '{{ .Values.postgresql.auth.username }}'
            - name: DB_NAME
              value: '{{ .Values.postgresql.auth.database }}'
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql-web-wallet
                  key: password
            - name: SPVWALLET_ADMIN_XPRIV
              {{- if .Values.global.adminkeySecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.adminkeySecret }}
                  key: {{ .Values.global.prvkey }}
              {{- else }}
              value: {{ .Values.config.prv_key | required "either adminSecret or prv_key is required" | quote }}
              {{- end }}
          envFrom:
            - configMapRef:
               name: {{ include "spv-wallet-web-backend.fullname" . }}
          {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }} 
          {{- end }} 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
