apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spv-wallet-admin.fullname" . }}
  labels:
    {{- include "spv-wallet-admin.labels" . | nindent 4 }}
data:
  env-config.json: |
    {
      {{- if .Values.config.loginTitle }}
      "loginTitle": "{{ .Values.config.loginTitle }}",
      {{- end }}
      {{- if .Values.config.loginTitle }}
      "loginSubtitle": "{{ .Values.config.loginSubtitle }}",
      {{- end }}
      {{- if .Values.config.serverUrl }}
      "serverUrl": "{{ .Values.config.serverUrl }}",
      {{- else }}
      "serverUrl": "https://{{ .Values.global.domainName }}/v1",
      {{- end }}
      "hideServerUrl": {{ .Values.config.hideServerUrl }}
    }
