apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-frontend-config
  labels:
    {{- include "bux-wallet-frontend.labels" . | nindent 4 }}
data:
  env-config.json: |
    {
      "apiUrl": "https://{{- .Release.Name}}-wallet-backend.{{ .Values.global.domainName }}",
      "paymailDomain": "{{ .Values.global.domainName }}"
    }