apiVersion: v1
kind: Service
metadata:
  name: {{ include "spv-wallet.fullname" . }}
  labels:
    {{- include "spv-wallet.labels" . | nindent 4 }}
  {{ if has "alb" $.Values.ingressControllers }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.global.domainName }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spv-wallet.selectorLabels" . | nindent 4 }}
