apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  labels:
    {{  include "bux-server.labels" . | nindent 4 }}
data:
  config.yaml: |-
    auth:
      require_signing: {{ .Values.config.auth.require_signing }}
      scheme: {{ .Values.config.auth.scheme }} 
      signing_disabled: {{ .Values.config.auth.signing_disabled }}
    cache:
      cluster:
        coordinator: {{ .Values.config.cache.cluster.coordinator }} 
        prefix: {{ .Values.config.cache.cluster.prefix }} 
        redis: {{ .Values.config.cache.cluster.redis }} 
      engine: {{ .Values.config.cache.engine }} 
      redis:
        dependency_mode: {{  .Values.config.cache.redis.dependency_mode }} 
        max_active_connections: {{  .Values.config.cache.redis.max_active_connections }} 
        max_connection_lifetime: {{  .Values.config.cache.redis.max_connection_lifetime }} 
        max_idle_connections: {{  .Values.config.cache.redis.max_idle_connections }} 
        max_idle_timeout: {{  .Values.config.cache.redis.max_idle_timeout }} 
        url: "redis://{{  .Release.Name}}-redis-master:6379"
        use_tls: {{  .Values.config.cache.redis.use_tls }} 
    db:
      datastore:
        debug: {{  .Values.config.db.datastore.debug }} 
        engine: {{  .Values.config.db.datastore.engine }} 
        table_prefix: {{  .Values.config.db.datastore.table_prefix }} 
      sql:
        debug: {{  .Values.config.db.sql.debug }} 
        driver: {{  .Values.config.db.sql.driver }} 
        host: "{{  .Release.Name}}-postgresql-server"
        max_connection_idle_time: {{  .Values.config.db.sql.max_connection_idle_time }} 
        max_connection_time: {{  .Values.config.db.sql.max_connection_time }} 
        max_idle_connections: {{  .Values.config.db.sql.max_idle_connections }} 
        max_open_connections: {{  .Values.config.db.sql.max_open_connections }} 
        name: {{  .Values.config.db.sql.name }} 
        password: {{  .Values.config.db.sql.password }} 
        port: {{  .Values.config.db.sql.port }} 
        replica: {{  .Values.config.db.sql.replica }} 
        skip_initialize_with_version: {{  .Values.config.db.sql.skip_initialize_with_version }} 
        table_prefix: {{  .Values.config.db.sql.table_prefix }} 
        time_zone: {{  .Values.config.db.sql.time_zone }} 
        tx_timeout: {{  .Values.config.db.sql.tx_timeout }} 
        user: {{  .Values.config.db.sql.user }} 
    debug: {{  .Values.config.debug }} 
    debug_profiling: {{  .Values.config.debug_profiling }} 
    disable_itc: {{  .Values.config.disable_itc }}
    nodes:
      protocol: {{  .Values.config.nodes.protocol }}
      # Uncomment and set the following if you want to use different method of broadcasting then default
      #  apis:
      #    - arc_url: 
      #      mapi_url: 
      #      token: 
      #      minerid: 
      use_mapi_fee_quotes: {{  .Values.config.nodes.use_mapi_fee_quotes }}
    paymail:
      beef:
        pulse_url: {{  .Values.config.paymail.beef.pulse_url }}
        use_beef: {{  .Values.config.paymail.beef.use_beef }}
      default_from_paymail: bux@{{  .Values.global.domainName }}
      default_note: {{  .Values.config.paymail.default_note }}
      domain_validation_enabled: {{  .Values.config.paymail.domain_validation_enabled }}
      domains:
        - "{{  .Values.global.domainName }}"
        {{- range .Values.config.paymail.domains }}
        - "{{.}}"
        {{- end }}
      enabled: {{  .Values.config.paymail.enabled }}
      sender_validation_enabled: {{  .Values.config.paymail.sender_validation_enabled }}
    request_logging: {{  .Values.config.request_logging }}
    server_config:
      idle_timeout: {{  .Values.config.server_config.idle_timeout }}
      port: {{  .Values.config.server_config.port }}
      read_timeout: {{  .Values.config.server_config.read_timeout }}
      write_timeout: {{  .Values.config.server_config.write_timeout }}
    task_manager:
      factory: {{  .Values.config.task_manager.factory }}
