apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
  labels:
    {{- include "bux-console.labels" . | nindent 4 }}
data:
  env-config.json: |
    {
      "serverUrl": "https://{{- .Release.Name}}-server.{{ .Values.global.domainName }}/v1",
      "hideServerUrl": false
    }